@url = http://localhost:8000/api/v1


@admin_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoic2hlaWxsYUBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3ODg2MjE4OTEsImV4cCI6MTc4ODYyMjc5MX0.CHy3hQzqpTIiYbEaOvj7iIJCbxSTdNDO1jwWAuqJytA
@seller_token=
@customer_token=

### Admin login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "sheilla@gmail.com",
    "password": "Pass123"
}

### Create admin user
POST {{url}}/users
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "Sheilla Mungai",
  "email": "sheilla@gmail.com",
  "password": "Pass123",
  "role": "admin",
  "phone": "0710101010"
}